### ISSUE TITLE
ICS file shows no data

### ISSUE THREAD

**Issue by crazyitalian041** [eoleedi/TimeTree-Exporter#49]
I was able to get the export from my network console in safari and the json file format looks good. 

{"since":1705559804544,"chunk":true,"events":[{"id":"c5604788574c45c091ec4256d37591e0","primary_id":"2532863870416139591","calendar_id":27045069,"uuid":"c5604788574c45c091ec4256d37591e0","category":1,"type":0,"author_id":13540154,"author_type":"User","title":"David","all_day":false,"start_at":1727474400000,"start_timezone":"America/Los_Angeles","end_at":1727478000000,"end_timezone":"America/Los_Angeles","label_id":1,"location":"","location_lat":null,"location_lon":null,"url":null,"note":null,"lunar":false,"attendees":[13540154],"recurrences":[],"recurring_uuid":null,"alerts":[60],"parent_id":null,"link_object_id":null,"link_object_id_string":null,"row_order":null,"attachment":{"virtual_user_attendees":[]},"like_count":0,"files":[],"deactivated_at":null,"pinned_at":null,"updated_at":1727108902532,"created_at":1727108902521}

Executing the command to list the input shows the following result:

timetree-exporter -v /Users/xxxxxxxx/Documents/TimeTree/response/cal.json
2024-09-23 13:20:02 [INFO] Parsing /Users/xxxxxxxx/Documents/TimeTree/response/cal.json 
2024-09-23 13:20:02 [DEBUG] Skipping memo event
                     uid: 8e32ceb9393740bd8fe89b3dab22b121 
                     summary: 'Lukas Graham' 
                     time: 2019-01-31 18:00:00 ~ 2019-01-31 19:00:00 
                      
2024-09-23 13:20:02 [DEBUG] Skipping birthday event
                     uid: ba5f73dd09c047d9bab88791c1328271 
                     summary: '' 
                     time: 1991-07-13 00:00:00 ~ 1991-07-13 00:00:00 
                      
2024-09-23 13:20:02 [INFO] A Total of 252/254 events added to the calendar 
2024-09-23 13:20:02 [INFO] The .ics calendar file is saved to /Users/xxxxxxxxx/Library/Python/3.9/bin/timetree.ics 

Importing the calendar shows one event in 2021 and one repeating Saturdays of the rest.

Unsure how to get it to work properly.

**Comment by crazyitalian041** [comment]
Note** On the latest version of MacOS Sequoia

**Comment by crazyitalian041** [comment]
Sample ics file data:

BEGIN:VEVENT
SUMMARY:Follow up with lawyer
DTSTART;TZID=America/Los_Angeles:20201123T103000
DTEND;TZID=America/Los_Angeles:20201123T113000
DTSTAMP:20240923T202002Z
UID:02b1e9bc13194a97ad868449b7b1984d
CREATED:20200919T050928Z
LAST-MODIFY:20200919T050928Z
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER:-PT15M
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Return Abercrombie&Fitch
DTSTART;TZID=America/Los_Angeles:20200921T110000
DTEND;TZID=America/Los_Angeles:20200921T120000
DTSTAMP:20240923T202002Z
UID:7f544f92d79b4bb4a3812a73612054c3
CREATED:20200919T032431Z
LAST-MODIFY:20200919T032431Z
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER:-PT15M
END:VALARM
END:VEVENT
BEGIN:VEVENT

**Comment by eoleedi** [comment]
Which calendar did you import into?
I've tested that the sample ics file you provide can be imported into Apple Calendar (cloud) and both events are shown correctly in the calendar. (On MacOS Sequoia)

> Importing the calendar shows one event in 2021 and one repeating Saturday of the rest.

Did you mean that 251 events are repeated on Saturdays?
