### ISSUE TITLE
Adding support for automatic downloads

### ISSUE THREAD

**Issue by smjonas** [eoleedi/TimeTree-Exporter#59]
Hey there, first of all thanks for the great work! I wanted to be able to export the TimeTree calendar data programmatically so I researched a bit and came across this repository:
https://github.com/dltkddnr04/timetree_ics_server/tree/main

To summarize, the steps required to download the data of all calendars are the following:
- Perform a PUT request to `https://timetreeapp.com/api/v1/auth/email/signin` and provide the username, password and a random UUID. You will receive a session cookie if the login was successful that you can use for all further requests.
- Send a POST request to  `https://timetreeapp.com/api/batch` to get a list of calendars (optional).
- Finally, send a request to `https://timetreeapp.com/api/v1/calendar/{calendar_id}/events/sync` to get the data of a single calendar as JSON.

Here is a gist implementing this (adjusted from the repo linked above): https://gist.github.com/smjonas/356b0c60610ab13a3145b010af2075f0

I thought I'd share my findings in case you want to integrate it into your project :)

**Comment by eoleedi** [comment]
Thank you for the findings. It's really helpful.

**Comment by eoleedi** [comment]
Work in progress #62

**Comment by eoleedi** [comment]
> Thank you for sharing your repository! I’m trying to use the tool, but I'm having some difficulty understanding how it works for automatic downloads.
> 
> timetree-exporter -o "C:\path\output.ics" -e [mail@example.com](mailto:mail@example.com) Enter your password:
> 
> 1. Calendrier
> 2. Famille
>    Which Calendar do you want to export? (Default to 1):
> 
> I receive a prompt to choose between calendars. Is there a way to select a specific calendar automatically without being prompted each time? Thanks again

No at the moment.
This is not related to this issue. Open another one if needed!

**Comment by eoleedi** [comment]
> Yes, I want to automate the process because I frequently modify my calendar. Additionally, I use iOS shortcuts to, for example, schedule alarms based on the calendar.

That's actually not the intended usage of this project. However, you could use bash script `expect` and `send` command as a workaround for now.

**Comment by sobricius** [comment]
> Yes, I want to automate the process because I frequently modify my calendar. Additionally, I use iOS shortcuts to, for example, schedule alarms based on the calendar.

I have a workaround for this, not sure if someone is interested.

**Comment by eoleedi** [comment]
@polzy It's now possible to specify the calendar code with the newest version
